{"name": "test_start_setup[city_hsinchu]", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Cannot start the 'com.wantoto.gomaji2' application. Visit https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/android/activity-startup.md for troubleshooting. Original error: 'com.gomaji.MainActivity' or 'com.wantoto.gomaji2.com.gomaji.MainActivity' never started. Visit https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/android/activity-startup.md for troubleshooting", "trace": "appium_case\\test_gomaji_android10.py:28: in test_start_setup\n    driver.start_activity(\"com.wantoto.gomaji2\",\"com.gomaji.MainActivity\")\nC:\\Users\\pc\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\appium\\webdriver\\extensions\\android\\activities.py:63: in start_activity\n    self.execute(Command.START_ACTIVITY, data)\nC:\\Users\\pc\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py:321: in execute\n    self.error_handler.check_response(response)\nC:\\Users\\pc\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\appium\\webdriver\\errorhandler.py:31: in check_response\n    raise wde\nC:\\Users\\pc\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\appium\\webdriver\\errorhandler.py:26: in check_response\n    super().check_response(response)\nC:\\Users\\pc\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py:242: in check_response\n    raise exception_class(message, screen, stacktrace)\nE   selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Cannot start the 'com.wantoto.gomaji2' application. Visit https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/android/activity-startup.md for troubleshooting. Original error: 'com.gomaji.MainActivity' or 'com.wantoto.gomaji2.com.gomaji.MainActivity' never started. Visit https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/android/activity-startup.md for troubleshooting"}, "parameters": [{"name": "set_city", "value": "'city_hsinchu'"}], "start": 1627454397065, "stop": 1627454429521, "uuid": "32d9af3c-fb9e-4927-9879-d9aee457b248", "historyId": "c8562e5a0fd493eb33d1a207170d1710", "testCaseId": "f3feed65eb45ccf1942eda9554788ba4", "fullName": "appium_case.test_gomaji_android10#test_start_setup", "labels": [{"name": "parentSuite", "value": "appium_case"}, {"name": "suite", "value": "test_gomaji_android10"}, {"name": "host", "value": "DESKTOP-KUIP11U"}, {"name": "thread", "value": "15860-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "appium_case.test_gomaji_android10"}]}